version: "3.8"

services:
  etcd:
    image: bitnami/etcd:3.5.4
    restart: unless-stopped
    env_file:
      - t/env/etcd
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"

  etcd_tls:
    image: bitnami/etcd:3.5.4
    restart: unless-stopped
    env_file:
      - t/env/etcd
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: https://0.0.0.0:12379
      ETCD_LISTEN_CLIENT_URLS: https://0.0.0.0:12379
      ETCD_CERT_FILE: /certs/etcd.pem
      ETCD_KEY_FILE: /certs/etcd.key
    ports:
      - "12379:12379"
      - "12380:12380"
    volumes:
      - ./t/certs:/certs

  backend:
    image: grpc-client-nginx-module-test-backend:latest
    restart: unless-stopped
    build:
      context: ./t/backend
      args:
        ENABLE_PROXY: ${ENABLE_PROXY}
    ports:
      - "50051:50051"
